// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcQ5SqMpFmAGVwdihtdpdN6pknWAHIrRM',
    appId: '1:607388174953:web:18b9eded67e983b862f0f8',
    messagingSenderId: '607388174953',
    projectId: 'laptop-harbor-da90c',
    authDomain: 'laptop-harbor-da90c.firebaseapp.com',
    storageBucket: 'laptop-harbor-da90c.firebasestorage.app',
    measurementId: 'G-ZRGN7NYP8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3fB4lpUrhHVoj84QeRgV5uCYwkOWHEm0',
    appId: '1:607388174953:android:b53ab84a7cd9930a62f0f8',
    messagingSenderId: '607388174953',
    projectId: 'laptop-harbor-da90c',
    storageBucket: 'laptop-harbor-da90c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD05YTKEAI1BivfohMKBsITpB8uN73iENI',
    appId: '1:607388174953:ios:a3edefc822ccfe3e62f0f8',
    messagingSenderId: '607388174953',
    projectId: 'laptop-harbor-da90c',
    storageBucket: 'laptop-harbor-da90c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD05YTKEAI1BivfohMKBsITpB8uN73iENI',
    appId: '1:607388174953:ios:a3edefc822ccfe3e62f0f8',
    messagingSenderId: '607388174953',
    projectId: 'laptop-harbor-da90c',
    storageBucket: 'laptop-harbor-da90c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcQ5SqMpFmAGVwdihtdpdN6pknWAHIrRM',
    appId: '1:607388174953:web:56a4f8bb7225b92d62f0f8',
    messagingSenderId: '607388174953',
    projectId: 'laptop-harbor-da90c',
    authDomain: 'laptop-harbor-da90c.firebaseapp.com',
    storageBucket: 'laptop-harbor-da90c.firebasestorage.app',
    measurementId: 'G-SC2KL562NY',
  );
}
